name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:

  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            args: --all-features


    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: rustup update
    - run: cargo build ${{ matrix.args }}
    - run: cargo test ${{ matrix.args }}

  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo fmt -- --check
    - run: cargo clippy
    - run: "! grep -r 'dbg!' ./src"

  conventional-commits:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: pip3 install -U Commitizen
      # The commit hash here is that of the commit where we started using conventional commits.
    - run: cz check --rev-range 5c1002b8..HEAD
