name: CI

on:
  push:
  schedule:
    - cron:  '0 0 * * 1' # weekly

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - run: rustup update
    - run: cargo build
    - run: cargo test

  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cargo fmt -- --check
    - run: cargo clippy
